<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMzTr2R4\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMzTr2R4/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMzTr2R4.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMzTr2R4\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMzTr2R4\App_KernelDevDebugContainer([
    'container.build_hash' => 'MzTr2R4',
    'container.build_id' => '086f288d',
    'container.build_time' => 1666873893,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMzTr2R4');
