<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDL7OyqG\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDL7OyqG/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDL7OyqG.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDL7OyqG\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDL7OyqG\App_KernelDevDebugContainer([
    'container.build_hash' => 'DL7OyqG',
    'container.build_id' => '27e6d174',
    'container.build_time' => 1666781825,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDL7OyqG');
